-- Uygulama PDB'sine gec (yoksa kullanicilar CDB kokunde COMMON olusur, PDB'de CREATE SESSION olmaz -> ORA-01045)
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER usersvc IDENTIFIED BY usersvc_2026;
GRANT CONNECT, RESOURCE TO usersvc;
ALTER USER usersvc QUOTA UNLIMITED ON USERS;

CREATE USER accountsvc IDENTIFIED BY accountsvc_2026;
GRANT CONNECT, RESOURCE TO accountsvc;
ALTER USER accountsvc QUOTA UNLIMITED ON USERS;

CREATE USER paymentsvc IDENTIFIED BY paymentsvc_2026;
GRANT CONNECT, RESOURCE TO paymentsvc;
ALTER USER paymentsvc QUOTA UNLIMITED ON USERS;